.PHONY: clean All

All:
	@echo "----------Building project:[ 06- opdracht 1 - Debug ]----------"
	@"$(MAKE)" -f  "06- opdracht 1.mk"
clean:
	@echo "----------Cleaning project:[ 06- opdracht 1 - Debug ]----------"
	@"$(MAKE)" -f  "06- opdracht 1.mk" clean
